### ISSUE TITLE
[Bug]: All entities are down

### ISSUE THREAD

**Issue by joostiphone** [mariusz-ostoja-swierczynski/tech-controllers#123] opened 2024-10-18 06:41 UTC
### The problem

All entities are not available and the integration doesn't seem to work. It worked perfectly fine for the last 6 months, but since yesterday it doesn't work anymore. Perhaps this is on TechControllers server side? 

### What version of Tech Controllers integration has the issue?

2.0.0

### What version of Home Assistant Core has the issue?

core-2024.10.2

### What was the last working version of Tech Controller integration?

2.0.0

### Diagnostics information

[home-assistant_tech_2024-10-18T06-37-45.845Z.log](https://github.com/user-attachments/files/17429408/home-assistant_tech_2024-10-18T06-37-45.845Z.log)

**Comment by anarion80** [comment] 2024-10-18 06:46
Yes, there seems to be an outage of emodul.eu/emodul.pl. The website is unreachable:

```bash
PING emodul.eu (20.126.131.255) 56(84) bytes of data.
From 20.126.131.255 (20.126.131.255) icmp_seq=1 Destination Host Unreachable
From 20.126.131.255 (20.126.131.255) icmp_seq=2 Destination Host Unreachable
From 20.126.131.255 (20.126.131.255) icmp_seq=3 Destination Host Unreachable
```

Hopefully this is just temporary...

**Comment by anarion80** [comment] 2024-10-18 07:38
Called their service line, the problem is known and they are working on it.

**Comment by joostiphone** [comment] 2024-10-18 07:46
Thanks for this!

**Comment by anarion80** [comment] 2024-10-18 11:33
Seems to back now, I will close the issue,

**Closed by anarion80** 2024-10-18 11:33 UTC
Labels: bug, triage
